USE Sample;
GO
CREATE TABLE Student(
				DEPT_ID INT ,
				NAME VARCHAR(50) NOT NULL,
				AGE INT,
				DEPT_NAME VARCHAR(50));
INSERT INTO Student VALUES(NULL,'AARON',20,'AI&DS'),(NULL,'SAM',21,'BIOTECH'),(3,'CHOKI',22,'AI&ML');
GO
CREATE TABLE Department(
					DEPT_ID INT PRIMARY KEY,
					DEPT_NAME VARCHAR(50),
					COURCES VARCHAR(100));
INSERT INTO Department VALUES(1,'AI&DS','AI'),(2,'AI&ML','ML'),(3,'BIOTECH','NANOMED');
GO
--EQUI JOIN
SELECT S.DEPT_ID, S.NAME, S.AGE, S.DEPT_NAME,D.DEPT_ID,D.COURCES,D.DEPT_NAME
FROM Student AS S,Department AS D
WHERE S.DEPT_ID=D.DEPT_ID;
GO
--NON -EQUI JOIN
SELECT S.DEPT_ID, S.NAME, S.AGE, S.DEPT_NAME,D.DEPT_ID,D.COURCES,D.DEPT_NAME
FROM Student AS S,Department AS D
WHERE S.DEPT_ID>=D.DEPT_ID;
SELECT S.DEPT_ID, S.NAME, S.AGE, S.DEPT_NAME,D.DEPT_ID,D.COURCES,D.DEPT_NAME
FROM Student AS S,Department AS D
WHERE S.DEPT_ID<>D.DEPT_ID;
SELECT S.DEPT_ID, S.NAME, S.AGE, S.DEPT_NAME,D.DEPT_ID,D.COURCES,D.DEPT_NAME
FROM Student AS S,Department AS D
WHERE S.DEPT_ID<=D.DEPT_ID;
GO
--SELF JOIN
SELECT S.DEPT_ID,S.NAME,S.AGE,S.DEPT_NAME,A.DEPT_ID,A.NAME,A.AGE,A.DEPT_NAME
FROM Student AS S, Student AS A
WHERE S.DEPT_ID=A.DEPT_ID;
GO
-- LEFT OUTER JOIN/LEFT JOIN
SELECT S.DEPT_ID, S.NAME, S.AGE, S.DEPT_NAME
FROM Student AS S
LEFT OUTER JOIN Department AS D ON S.DEPT_ID = D.DEPT_ID;
SELECT S.DEPT_ID, S.NAME, S.AGE, S.DEPT_NAME
FROM Student AS S
LEFT JOIN Department AS D ON S.DEPT_ID = D.DEPT_ID;
GO
--RIGHT OUTER JOIN/RIGHT JOIN
SELECT S.DEPT_ID,S.NAME,S.AGE,S.DEPT_NAME
FROM Student AS S
RIGHT OUTER JOIN Department AS D ON S.DEPT_ID=D.DEPT_ID;
GO
SELECT D.DEPT_ID, D.DEPT_NAME,D.COURCES
FROM Department AS D
RIGHT JOIN Student AS S ON D.DEPT_ID = S.DEPT_ID;
GO
--FULL JOIN/FULL OUTER JOIN
SELECT S.DEPT_ID,S.NAME,S.AGE,S.DEPT_NAME,D.DEPT_ID,D.COURCES,D.DEPT_NAME
FROM Student AS S
FULL JOIN Department AS D ON S.DEPT_ID=D.DEPT_ID;
SELECT S.DEPT_ID,S.NAME,S.AGE,S.DEPT_NAME,D.DEPT_ID,D.COURCES,D.DEPT_NAME
FROM Student AS S
FULL  OUTER JOIN Department AS D ON S.DEPT_ID=D.DEPT_ID;
GO
--INNER JOIN
SELECT S.DEPT_ID, S.NAME, S.AGE, S.DEPT_NAME
FROM Student AS S
INNER JOIN Department AS D ON S.DEPT_ID = D.DEPT_ID;
GO
--CROSS JOIN/CARTESIAN PRODUCT
SELECT S.DEPT_ID, S.NAME, S.AGE, S.DEPT_NAME,D.DEPT_ID,D.COURCES,D.DEPT_NAME
FROM Student AS S
CROSS JOIN Department D;
SELECT S.DEPT_ID, S.NAME, S.AGE, S.DEPT_NAME,D.DEPT_ID,D.COURCES,D.DEPT_NAME
FROM Student AS S, Department AS D;
GO
--SET OPERATERS
--UNTION
SELECT DEPT_ID FROM Student 
UNION 
SELECT DEPT_ID FROM Department;
GO
--UNION ALL
SELECT DEPT_ID FROM Student 
UNION ALL 
SELECT DEPT_ID FROM Department;
GO
--INTERSECT
SELECT DEPT_ID FROM Student 
INTERSECT 
SELECT DEPT_ID FROM Department;
GO
--MINUS
SELECT DEPT_ID FROM Student 
MINUS 
SELECT DEPT_ID FROM Department;
GO
-- SAMPLE PARITION EX
SELECT 
    S.DEPT_ID, 
    S.DEPT_NAME,
    AVG(S.AGE) OVER (PARTITION BY S.DEPT_ID) AS AvgAge
FROM 
    Student AS S;
GO



