-- Create database
CREATE DATABASE CompanyData;
GO

-- Use the database
USE CompanyData;
GO

-- Create the DEPARTMENTS table 
CREATE TABLE DEPARTMENTS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);
GO

-- Insert sample data into DEPARTMENTS
INSERT INTO DEPARTMENTS (ID, NAME) 
VALUES 
(1, 'HR'), (2, 'Finance'), (3, 'Software Developer'),
(4, 'Hardware Developer'), (5, 'Tester');
GO

-- Create the EMPLOYEES table 
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(25) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    SALARY DECIMAL(10,2) NOT NULL,
    DEPARTMENT_ID INT,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID)
);
GO

-- Insert sample data into EMPLOYEES
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID) 
VALUES 
(101, 'Aaron', 'Sam', 50000.00, 1),
(102, 'Mickey', 'Choki', 60000.00, 2),
(103, 'Choki', 'Mickey', 55000.00, 3),
(104, 'Sobana', 'RS', 85000.00, 4),
(105, 'Tomie', 'AS', 90000.00, 5);
GO

-- Create the TRG_DEPT table
CREATE TABLE TRG_DEPT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL
);
GO

-- Populate TRG_DEPT table with data from DEPARTMENTS
INSERT INTO TRG_DEPT (ID, NAME)
SELECT ID, NAME FROM DEPARTMENTS;
GO

-- Populate DEPT101 table with data from DEPARTMENTS
SELECT ID, NAME
INTO DEPT101
FROM DEPARTMENTS;
GO

-- Create the TRG_EMP table
CREATE TABLE TRG_EMP (
    ID INT PRIMARY KEY,
    LAST_NAME VARCHAR(25) NOT NULL,
    FIRST_NAME VARCHAR(25) NOT NULL,
    DEPT_ID INT,
    FOREIGN KEY (DEPT_ID) REFERENCES TRG_DEPT(ID)
);
GO

-- Modify TRG_EMP to allow longer employee last names
ALTER TABLE TRG_EMP 
ALTER COLUMN LAST_NAME VARCHAR(50);
GO

-- Create the TRG_EMPLOYEES table based on EMPLOYEES
SELECT EMPLOYEE_ID AS ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID AS DEPT_ID
INTO TRG_EMPLOYEES
FROM EMPLOYEES;
GO

-- Drop the TRG_EMP table
DROP TABLE TRG_EMP;
GO

-- Rename TRG_EMPLOYEES table to TRG_EMP
EXEC sp_rename 'dbo.TRG_EMPLOYEES', 'TRG_EMP';
GO

-- Drop the FIRST_NAME column from TRG_EMP
ALTER TABLE TRG_EMP
DROP COLUMN FIRST_NAME;
GO

-- Retrieve all data from the tables
SELECT * FROM DEPT101;
SELECT * FROM TRG_EMP;
SELECT * FROM TRG_DEPT;
GO
