CREATE DATABASE CASESTUDY;
USE CASESTUDY;
GO
--CREATE TABLE EMPLOYEES
CREATE TABLE Employees(
					EMPLOYEE_ID INT PRIMARY KEY,
					NAME VARCHAR(20),
					DEPARTMENT VARCHAR(20),
					MAIL VARCHAR(25),
					PASSWORD VARCHAR(30));
GO
--CREATION OF TABLE ASSETS
CREATE TABLE Assets(
				ASSET_ID INT PRIMARY KEY,
				NAME VARCHAR(20),
				TYPE VARCHAR(20),
				SERIAL_NO VARCHAR(25) UNIQUE,
				PUR_DATE DATE,
				LOCATION VARCHAR(30),
				STATUS VARCHAR(40),
				OWNER_ID INT,
				CONSTRAINT FK_ASSET_OWNER FOREIGN KEY(OWNER_ID) REFERENCES Employees(EMPLOYEE_ID));
GO
--CREATION OF TABLE MAINTENANCE_RECORD
CREATE TABLE Maintenance_record(
							MAINTENANCE_ID INT PRIMARY KEY,
							ASSET_ID INT,
							MAINTENANCE_DATE DATE,
							DESCRIPTION VARCHAR(50),
							COST DECIMAL(10,2),
							CONSTRAINT FK_MAINTENANCE FOREIGN KEY(ASSET_ID) REFERENCES Assets(ASSET_ID));
GO
--CREATION OF TABLE ASSET_ALLOCATION
CREATE TABLE Asset_allocation(
							ALLOCATION_ID INT PRIMARY KEY,
							ASSET_ID INT,
							EMPLOYEE_ID INT,
							ALLOCATION_DATE DATE,
							RETURN_DATE DATE,
							FOREIGN KEY(ASSET_ID) REFERENCES Assets(ASSET_ID),
							FOREIGN KEY(EMPLOYEE_ID) REFERENCES Employees(EMPLOYEE_ID));
GO
--CREATION OF TABLE RESERVATIONS
CREATE TABLE Reservations(
						RESERVATION_ID INT PRIMARY KEY,
						ASSET_ID INT,
						EMPLOYEE_ID INT,
						RESERVATION_DATE DATE,
						START_DATE DATE,
						END_DATE DATE,
						STATUS VARCHAR (30),
						FOREIGN KEY(ASSET_ID) REFERENCES Assets(ASSET_ID),
						FOREIGN KEY(EMPLOYEE_ID) REFERENCES Employees(EMPLOYEE_ID));
GO
				

