--CASE STUDY-CRIME REPORTING SYSTEM
USE CASESTUDY;
GO
-- Victims Table
CREATE TABLE VICTIMS (
    VICTIM_ID INT PRIMARY KEY ,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    DATEOFBIRTH DATE,
    GENDER VARCHAR(10),
    CONTACTINFO NVARCHAR(255)
);
GO
-- Suspects Table
CREATE TABLE SUSPECTS (
    SUSPECT_ID INT PRIMARY KEY,
    FIRSTNAME NVARCHAR(100),
    LASTNAME NVARCHAR(100),
    DATEOFBIRTH DATE,
    GENDER NVARCHAR(10),
    CONTACTINFO NVARCHAR(255)
);
GO
-- Law Enforcement Agencies Table
CREATE TABLE LAW_ENFORCEMENT_AGENCIES (
    AGENCYID INT PRIMARY KEY ,
    AGENCYNAME VARCHAR(100),
    JURISDICTION VARCHAR(100),
    CONTACTINFO NVARCHAR(255)
);
GO
-- CREATE OFFICERS TABLE
CREATE TABLE OFFICERS (
    OFFICER_ID INT PRIMARY KEY IDENTITY(1,1),
    FIRSTNAME VARCHAR(100),
    LASTNAME VARCHAR(100),
    BADGENUMBER NVARCHAR(50),
    RANK NVARCHAR(50),
    CONTACTINFO NVARCHAR(255),
    AGENCYID INT,
    CONSTRAINT FK_OFFICER_AGENCY FOREIGN KEY (AGENCYID) REFERENCES LAW_ENFORCEMENT_AGENCIES(AGENCYID)
);
GO
--CREATE INCIDENTS TABLE
CREATE TABLE INCIDENTS (
    INCIDENT_ID INT PRIMARY KEY,
    INCIDENTTYPE NVARCHAR(100),
    INCIDENTDATE DATETIME,
    LOCATION NVARCHAR(255),
    DESCRIPTION NVARCHAR(255),
    STATUS NVARCHAR(50),
    VICTIMID INT,
    SUSPECTID INT,
    CONSTRAINT FK_INCIDENT_VICTIM FOREIGN KEY (VICTIMID) REFERENCES VICTIMS(VICTIM_ID),
    CONSTRAINT FK_INCIDENT_SUSPECT FOREIGN KEY (SUSPECTID) REFERENCES SUSPECTS(SUSPECT_ID)
);
GO
-- CREATE REPORT TABLE
CREATE TABLE EVIDENCE (
    EVIDENCE_ID INT PRIMARY KEY,
    DESCRIPTION NVARCHAR(255),
    LOCATIONFOUND NVARCHAR(255),
    INCIDENT_ID INT,
    CONSTRAINT FK_EVIDENCE_INCIDENT FOREIGN KEY (INCIDENT_ID) REFERENCES INCIDENTS(INCIDENT_ID)
);

-- CREATE REPORT TABLE
CREATE TABLE REPORTS (
    REPORT_ID INT PRIMARY KEY IDENTITY(1,1),
    INCIDENT_ID INT,
    REPORTINGOFFICER INT,
    REPORTDATE DATETIME,
    REPORTDETAILS NVARCHAR(255),
    STATUS NVARCHAR(50),
    CONSTRAINT FK_REPORT_INCIDENT FOREIGN KEY (INCIDENT_ID) REFERENCES INCIDENTS(INCIDENT_ID),
    CONSTRAINT FK_REPORT_OFFICER FOREIGN KEY (REPORTINGOFFICER) REFERENCES OFFICERS(OFFICER_ID)
);

