--CASE STUDY -CARCONNECT
USE CASESTUDY;
GO
--CREATION OF TABLE CUSTOMER
CREATE TABLE Customer(
					CUSTOMER_ID INT PRIMARY KEY,
					FIRST_NAME VARCHAR(30),
					LAST_NAME VARCHAR(30),
					EMAIL VARCHAR(30) UNIQUE,
					PHONE_NO INT UNIQUE,
					ADDRESS VARCHAR(100),
					USERNAME VARCHAR(30),
					PASSWORD VARCHAR(40),
					REGISTRATION_DATE DATE);
GO
--CREATION OD TABLE VEHICLE
CREATE TABLE Vehicle(
					VECHILE_ID INT PRIMARY KEY,
					MODEL VARCHAR(30),
					MAKE VARCHAR(30),
					YEAR INT,
					COLOR VARCHAR(20),
					REGISTRATION_NO INT UNIQUE,
					AVAILABILITY NVARCHAR(10),
					DAILYRENT DECIMAL(9,2));
GO
--CREATION OF TABLE RESERVATION
CREATE TABLE Reservention_table(
							REGISTRATION_ID INT PRIMARY KEY,
							CUSTOMER_ID INT,
							VECHILE_ID INT,
							START_DATE DATE,
							END_END DATE,
							TOTAL_COST DECIMAL(10,2),
							STATUS VARCHAR(30),
							FOREIGN KEY(CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID),
							FOREIGN KEY(VECHILE_ID) REFERENCES Vehicle(VECHILE_ID));
GO
--CREATION OF TABLE ADMIN
CREATE TABLE Admin(
				ADMIN_ID INT PRIMARY KEY,
				FIRST_NAME VARCHAR(30),
				LAST_NAME VARCHAR(30),
				EMAIL VARCHAR(30),
				PHONE_NO INT UNIQUE,
				USERNAME VARCHAR(50),
				PASSWORD VARCHAR(50) UNIQUE,
				ROLE VARCHAR(30),
				JOIN_DATE DATE);
