--CASE STUDY -VIRTUAL ART GALLERY
USE CASESTUDY;
GO
-- Artist Table
CREATE TABLE ARTIST (
    ARTISTID INT PRIMARY KEY IDENTITY(1,1),
    NAME NVARCHAR(100),
    BIOGRAPHY NVARCHAR(1000),
    BIRTHDATE DATE,
    NATIONALITY NVARCHAR(100),
    WEBSITE NVARCHAR(255),
    CONTACTINFO NVARCHAR(255)
);

-- Artwork Table
CREATE TABLE ARTWORK (
    ARTWORKID INT PRIMARY KEY IDENTITY(1,1),
    TITLE NVARCHAR(255),
    DESCRIPTION NVARCHAR(1000),
    CREATIONDATE DATE,
    MEDIUM NVARCHAR(100),
    IMAGEURL NVARCHAR(255),
    ARTISTID INT,
    CONSTRAINT FK_ARTWORK_ARTIST FOREIGN KEY (ARTISTID) REFERENCES ARTIST(ARTISTID)
);

-- User Table 
CREATE TABLE [USER] (--GIVEN THE USER IN[]  BECAUSE IT IS A RESERVED KEYWORD IN MS SQL
    USERID INT PRIMARY KEY IDENTITY(1,1),
    USERNAME NVARCHAR(100),
    PASSWORD NVARCHAR(255),
    EMAIL NVARCHAR(255),
    FIRSTNAME NVARCHAR(100),
    LASTNAME NVARCHAR(100),
    DATEOFBIRTH DATE,
    PROFILEPICTURE NVARCHAR(255)
);

-- User_Favorite_Artwork Table (junction table for many-to-many relationship)
CREATE TABLE USER_FAVORITE_ARTWORK (
    USERID INT,
    ARTWORKID INT,
    PRIMARY KEY (USERID, ARTWORKID),
    CONSTRAINT FK_USER_FAVORITE_USER FOREIGN KEY (USERID) REFERENCES [USER](USERID),
    CONSTRAINT FK_USER_FAVORITE_ARTWORK FOREIGN KEY (ARTWORKID) REFERENCES ARTWORK(ARTWORKID)
);

-- Gallery Table
CREATE TABLE GALLERY (
    GALLERYID INT PRIMARY KEY IDENTITY(1,1),
    NAME NVARCHAR(255),
    DESCRIPTION NVARCHAR(1000),
    LOCATION NVARCHAR(255),
    ARTISTID INT,
    OPENINGHOURS NVARCHAR(255),
    CONSTRAINT FK_GALLERY_ARTIST FOREIGN KEY (ARTISTID) REFERENCES ARTIST(ARTISTID)
);

-- Artwork_Gallery Table (junction table for many-to-many relationship)
CREATE TABLE ARTWORK_GALLERY (
    ARTWORKID INT,
    GALLERYID INT,
    PRIMARY KEY (ARTWORKID, GALLERYID),
    CONSTRAINT FK_ARTWORK_GALLERY_ARTWORK FOREIGN KEY (ARTWORKID) REFERENCES ARTWORK(ARTWORKID),
    CONSTRAINT FK_ARTWORK_GALLERY_GALLERY FOREIGN KEY (GALLERYID) REFERENCES GALLERY(GALLERYID)
);
